import React, { createContext, useState, useContext, ReactNode } from 'react';

export enum Language {
  ENGLISH = 'en',
  HINDI = 'hi',
  PUNJABI = 'pa',
  TAMIL = 'ta',
  MARATHI = 'mr'
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  [Language.ENGLISH]: {
    'nav.home': 'Home',
    'nav.donate': 'Donate',
    'nav.request': 'Request',
    'nav.ngo': 'NGO Portal',
    'nav.gov': 'Government',
    'nav.about': 'About',
    'nav.translate': 'Translate',
    'nav.signin': 'Sign In',
    'nav.getstarted': 'Get Started',
    'nav.logout': 'Logout',
    'hero.badge': 'Smart Medicine Redistribution Network',
    'hero.title': 'Transforming unused medicines into life-saving resources',
    'hero.desc': 'Join our network to reduce pharmaceutical waste, save lives, and build a sustainable healthcare ecosystem through intelligent medicine redistribution.',
    'hero.donate': 'Donate medicine',
    'hero.request': 'Request medicines',
    'hero.partner': 'Become a partner',
    'stats.saved': 'Medicines Saved (units)',
    'stats.lives': 'Lives Impacted',
    'stats.co2': 'CO₂ Reduced (kg)',
    'stats.waste': 'Waste Prevented (₹)',
    'map.title': 'Live Medicine Distribution Network',
    'map.desc': 'Track real-time medicine flows, drop-box locations, and active delivery routes across the city',
    'map.dropbox': 'Drop-box Locations',
    'map.routes': 'Active Routes',
    'map.delivered': 'Delivered Today',
    'how.title': 'How It Works',
    'how.desc': 'Simple, transparent, and efficient medicine redistribution in three steps',
    'how.step1.title': 'Collect',
    'how.step1.desc': 'Donors drop off unused medicines at verified collection points or schedule home pickup. Every donation is tracked and recorded.',
    'how.step2.title': 'Verify',
    'how.step2.desc': 'Our licensed pharmacists and verified systems perform a rigorous clinical audit on every batch to ensure absolute safety and authenticity.',
    'how.step3.title': 'Redirect',
    'how.step3.desc': 'Medicines are redistributed to verified NGOs, clinics, and patients in need through our secure logistics network.',
    'cta.title': 'Join the Life-saving Grid',
    'cta.desc': "Don't let medicines go to waste. Join thousands making healthcare accessible for all.",
    'cta.start': 'Start donating now',
    'cta.learn': 'Learn more',
    'auth.welcome': 'Welcome Back!',
    'auth.join': 'Join the Grid',
    'auth.loginDesc': 'To keep connected with us please login with your personal info',
    'auth.regDesc': 'Enter your personal details and start journey with us',
    'auth.create': 'Create Account',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.google': 'Sign in with Google',
    'auth.emailOr': 'or use your email for',
    'auth.login': 'login',
    'auth.registration': 'registration',
    'auth.identity': 'Select Identity',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.remember': 'Remember me',
    'auth.forgot': 'Forgot password?',
    'auth.back': 'Back to Home',
    'donor.title': 'Donor Dashboard',
    'donor.subtitle': 'Track your impact and manage your donations',
    'donor.donate': 'Donate Medicine',
    'donor.history': 'Donation History',
    'donor.impact': 'Your Impact',
    'donor.saved': 'Medicines Saved',
    'donor.lives': 'Lives Impacted',
    'donor.points': 'MedPoints Earned',
    'receiver.title': 'Request Center',
    'receiver.subtitle': 'Verified pharmaceutical surplus available for those in need.',
    'receiver.newRequest': 'New Medicine Request',
    'receiver.log': 'Your Health Log',
    'receiver.ayushman': 'Validate Ayushman ID',
    'receiver.ayushmanPlaceholder': 'Enter Ayushman ID (e.g. ABC)',
    'receiver.validate': 'Validate Account',
    'receiver.invalidId': 'Invalid Ayushman ID. Please use "ABC" for prototype simulation.',
    'receiver.uploadPrescription': 'Upload Prescription',
    'receiver.prescriptionDesc': 'Please upload your medical prescription for verification.',
    'receiver.verifying': 'Verifying Prescription...',
    'receiver.verified': 'Verified Prescription',
    'receiver.verifiedDesc': 'Your prescription has been verified. You can now schedule delivery.',
    'receiver.schedule': 'Schedule Delivery',
    'receiver.scheduling': 'Scheduling Delivery...',
    'receiver.scheduled': 'Delivery Scheduled',
    'receiver.arrival': 'Estimated Arrival',
    'receiver.otp': 'Delivery OTP',
    'receiver.otpDesc': 'Show this OTP to the delivery partner.',
    'receiver.history': 'Previous Requests',
    'receiver.status.uploaded': 'Prescription Uploaded',
    'receiver.status.verified': 'Verified Prescription',
    'receiver.status.scheduled': 'Delivery Scheduled',
    'receiver.status.completed': 'Completed'
  },
  [Language.HINDI]: {
    'nav.home': 'होम',
    'nav.donate': 'दान करें',
    'nav.request': 'अनुरोध',
    'nav.ngo': 'एनजीओ पोर्टल',
    'nav.gov': 'सरकार',
    'nav.about': 'हमारे बारे में',
    'nav.translate': 'अनुवाद',
    'nav.signin': 'साइन इन',
    'nav.getstarted': 'शुरू करें',
    'nav.logout': 'लॉगआउट',
    'hero.badge': 'स्मार्ट मेडिसिन पुनर्वितरण नेटवर्क',
    'hero.title': 'अप्रयुक्त दवाओं को जीवन रक्षक संसाधनों में बदलना',
    'hero.desc': 'फार्मास्युटिकल कचरे को कम करने, जीवन बचाने और बुद्धिमान दवा पुनर्वितरण के माध्यम से एक स्थायी स्वास्थ्य सेवा पारिस्थितिकी तंत्र बनाने के लिए हमारे नेटवर्क में शामिल हों।',
    'hero.donate': 'दवा दान करें',
    'hero.request': 'दवाओं का अनुरोध करें',
    'hero.partner': 'पार्टनर बनें',
    'stats.saved': 'बचाई गई दवाएं (यूनिट)',
    'stats.lives': 'प्रभावित जीवन',
    'stats.co2': 'CO₂ कम हुआ (किग्रा)',
    'stats.waste': 'बचाया गया कचरा (₹)',
    'map.title': 'लाइव मेडिसिन वितरण नेटवर्क',
    'map.desc': 'शहर भर में रीयल-टाइम दवा प्रवाह, ड्रॉप-बॉक्स स्थानों और सक्रिय वितरण मार्गों को ट्रैक करें',
    'map.dropbox': 'ड्रॉप-बॉक्स स्थान',
    'map.routes': 'सक्रिय मार्ग',
    'map.delivered': 'आज वितरित',
    'how.title': 'यह कैसे काम करता है',
    'how.desc': 'तीन चरणों में सरल, पारदर्शी और कुशल दवा पुनर्वितरण',
    'how.step1.title': 'संग्रह',
    'how.step1.desc': 'दाता अप्रयुक्त दवाओं को सत्यापित संग्रह बिंदुओं पर छोड़ते हैं या होम पिकअप शेड्यूल करते हैं। हर दान को ट्रैक और रिकॉर्ड किया जाता है।',
    'how.step2.title': 'सत्यापन',
    'how.step2.desc': 'हमारे लाइसेंस प्राप्त फार्मासिस्ट और सत्यापित सिस्टम पूर्ण सुरक्षा और प्रामाणिकता सुनिश्चित करने के लिए हर बैच पर कठोर नैदानिक ऑडिट करते हैं।',
    'how.step3.title': 'पुनर्निर्देशन',
    'how.step3.desc': 'दवाओं को हमारे सुरक्षित रसद नेटवर्क के माध्यम से सत्यापित एनजीओ, क्लीनिकों और जरूरतमंद मरीजों को पुनर्वितरित किया जाता है।',
    'cta.title': 'जीवन रक्षक ग्रिड में शामिल हों',
    'cta.desc': 'दवाओं को बर्बाद न होने दें। सभी के लिए स्वास्थ्य सेवा को सुलभ बनाने वाले हजारों लोगों में शामिल हों।',
    'cta.start': 'अभी दान करना शुरू करें',
    'cta.learn': 'अधिक जानें',
    'auth.welcome': 'वापसी पर स्वागत है!',
    'auth.join': 'ग्रिड में शामिल हों',
    'auth.loginDesc': 'हमसे जुड़े रहने के लिए कृपया अपनी व्यक्तिगत जानकारी के साथ लॉगिन करें',
    'auth.regDesc': 'अपना व्यक्तिगत विवरण दर्ज करें और हमारे साथ यात्रा शुरू करें',
    'auth.create': 'खाता बनाएं',
    'auth.signin': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.google': 'गूगल के साथ साइन इन करें',
    'auth.emailOr': 'या ईमेल का उपयोग करें',
    'auth.login': 'लॉगिन',
    'auth.registration': 'पंजीकरण',
    'auth.identity': 'पहचान चुनें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.remember': 'मुझे याद रखें',
    'auth.forgot': 'पासवर्ड भूल गए?',
    'auth.back': 'होम पर वापस जाएं',
    'donor.title': 'दाता डैशबोर्ड',
    'donor.subtitle': 'अपने प्रभाव को ट्रैक करें और अपने दान प्रबंधित करें',
    'donor.donate': 'दवा दान करें',
    'donor.history': 'दान इतिहास',
    'donor.impact': 'आपका प्रभाव',
    'donor.saved': 'बचाई गई दवाएं',
    'donor.lives': 'प्रभावित जीवन',
    'donor.points': 'मेडपॉइंट्स अर्जित',
    'receiver.title': 'अनुरोध केंद्र',
    'receiver.subtitle': 'जरूरतमंदों के लिए सत्यापित फार्मास्युटिकल अधिशेष उपलब्ध है।',
    'receiver.newRequest': 'नया दवा अनुरोध',
    'receiver.log': 'आपका स्वास्थ्य लॉग',
    'receiver.ayushman': 'आयुष्मान आईडी सत्यापित करें',
    'receiver.ayushmanPlaceholder': 'आयुष्मान आईडी दर्ज करें (जैसे ABC)',
    'receiver.validate': 'खाता सत्यापित करें',
    'receiver.invalidId': 'अमान्य आयुष्मान आईडी। कृपया प्रोटोटाइप सिमुलेशन के लिए "ABC" का उपयोग करें।',
    'receiver.uploadPrescription': 'प्रिस्क्रिप्शन अपलोड करें',
    'receiver.prescriptionDesc': 'कृपया सत्यापन के लिए अपना मेडिकल प्रिस्क्रिप्शन अपलोड करें।',
    'receiver.verifying': 'प्रिस्क्रिप्शन सत्यापित किया जा रहा है...',
    'receiver.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.verifiedDesc': 'आपका प्रिस्क्रिप्शन सत्यापित हो गया है। अब आप डिलीवरी शेड्यूल कर सकते हैं।',
    'receiver.schedule': 'डिलीवरी शेड्यूल करें',
    'receiver.scheduling': 'डिलीवरी शेड्यूल की जा रही है...',
    'receiver.scheduled': 'डिलीवरी शेड्यूल की गई',
    'receiver.arrival': 'अनुमानित आगमन',
    'receiver.otp': 'डिलीवरी ओटीपी',
    'receiver.otpDesc': 'डिलीवरी पार्टनर को यह ओटीपी दिखाएं।',
    'receiver.history': 'पिछले अनुरोध',
    'receiver.status.uploaded': 'प्रिस्क्रिप्शन अपलोड किया गया',
    'receiver.status.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.status.scheduled': 'डिलीवरी शेड्यूल की गई',
    'receiver.status.completed': 'पूरा हुआ'
  },
  [Language.PUNJABI]: {
    'nav.home': 'ਹੋਮ',
    'nav.donate': 'ਦਾਨ ਕਰੋ',
    'nav.request': 'ਬੇਨਤੀ',
    'nav.ngo': 'ਐਨਜੀਓ ਪੋਰਟਲ',
    'nav.gov': 'ਸਰਕਾਰ',
    'nav.about': 'ਬਾਰੇ',
    'nav.translate': 'ਅਨੁਵਾਦ',
    'nav.signin': 'ਸਾਈਨ ਇਨ',
    'nav.getstarted': 'ਸ਼ੁਰੂ ਕਰੋ',
    'nav.logout': 'ਲੌਗਆਉਟ',
    'hero.badge': 'ਸਮਾਰਟ ਮੈਡੀਸਨ ਮੁੜ ਵੰਡ ਨੈੱਟਵਰਕ',
    'hero.title': 'ਅਣਵਰਤੀਆਂ ਦਵਾਈਆਂ ਨੂੰ ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ ਸਰੋਤਾਂ ਵਿੱਚ ਬਦਲਣਾ',
    'hero.desc': 'ਫਾਰਮਾਸਿਊਟੀਕਲ ਰਹਿੰਦ-ਖੂੰਹਦ ਨੂੰ ਘਟਾਉਣ, ਜਾਨਾਂ ਬਚਾਉਣ ਅਤੇ ਬੁੱਧੀਮਾਨ ਦਵਾਈਆਂ ਦੀ ਮੁੜ ਵੰਡ ਰਾਹੀਂ ਇੱਕ ਟਿਕਾਊ ਸਿਹਤ ਸੰਭਾਲ ਪ੍ਰਣਾਲੀ ਬਣਾਉਣ ਲਈ ਸਾਡੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ।',
    'hero.donate': 'ਦਵਾਈ ਦਾਨ ਕਰੋ',
    'hero.request': 'ਦਵਾਈਆਂ ਦੀ ਬੇਨਤੀ ਕਰੋ',
    'hero.partner': 'ਭਾਈਵਾਲ ਬਣੋ',
    'stats.saved': 'ਬਚਾਈਆਂ ਗਈਆਂ ਦਵਾਈਆਂ (ਯੂਨਿਟ)',
    'stats.lives': 'ਪ੍ਰਭਾਵਿਤ ਜੀਵਨ',
    'stats.co2': 'CO₂ ਘਟਾਇਆ (ਕਿਲੋ)',
    'stats.waste': 'ਰੋਕੀ ਗਈ ਰਹਿੰਦ-ਖੂੰਹਦ (ਭਾਰਤੀ ਰੁਪਏ)',
    'map.title': 'ਲਾਈਵ ਮੈਡੀਸਨ ਵੰਡ ਨੈੱਟਵਰਕ',
    'map.desc': 'ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ ਰੀਅਲ-ਟਾਈਮ ਦਵਾਈਆਂ ਦੇ ਪ੍ਰਵਾਹ, ਡ੍ਰੌਪ-ਬਾਕਸ ਸਥਾਨਾਂ ਅਤੇ ਸਰਗਰਮ ਡਿਲੀਵਰੀ ਰੂਟਾਂ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ',
    'map.dropbox': 'ਡ੍ਰੌਪ-ਬਾਕਸ ਸਥਾਨ',
    'map.routes': 'ਸਰਗਰਮ ਰੂਟ',
    'map.delivered': 'ਅੱਜ ਡਿਲੀਵਰ ਕੀਤਾ ਗਿਆ',
    'how.title': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    'how.desc': 'ਤਿੰਨ ਕਦਮਾਂ ਵਿੱਚ ਸਰਲ, ਪਾਰਦਰਸ਼ੀ ਅਤੇ ਕੁਸ਼ਲ ਦਵਾਈਆਂ ਦੀ ਮੁੜ ਵੰਡ',
    'how.step1.title': 'ਇਕੱਠਾ ਕਰਨਾ',
    'how.step1.desc': 'ਦਾਨੀ ਅਣਵਰਤੀਆਂ ਦਵਾਈਆਂ ਨੂੰ ਪ੍ਰਮਾਣਿਤ ਸੰਗ੍ਰਹਿ ਬਿੰਦੂਆਂ ਤੇ ਛੱਡਦੇ ਹਨ ਜਾਂ ਹੋਮ ਪਿਕਅੱਪ ਤੈਅ ਕਰਦੇ ਹਨ। ਹਰ ਦਾਨ ਨੂੰ ਟ੍ਰੈਕ ਅਤੇ ਰਿਕਾਰਡ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।',
    'how.step2.title': 'ਪੜਤਾਲ',
    'how.step2.desc': 'ਸਾਡੇ ਲਾਇਸੰਸਸ਼ੁਦਾ ਫਾਰਮਾਸਿਸਟ ਅਤੇ ਪ੍ਰਮਾਣਿਤ ਸਿਸਟਮ ਪੂਰਨ ਸੁਰੱਖਿਆ ਅਤੇ ਪ੍ਰਮਾਣਿਕਤਾ ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਣ ਲਈ ਹਰ ਬੈਚ ਤੇ ਸਖ਼ਤ ਕਲੀਨਿਕਲ ਆਡਿਟ ਕਰਦੇ ਹਨ।',
    'how.step3.title': 'ਮੁੜ ਵੰਡ',
    'how.step3.desc': 'ਦਵਾਈਆਂ ਸਾਡੇ ਸੁਰੱਖਿਅਤ ਲੌਜਿਸਟਿਕਸ ਨੈੱਟਵਰਕ ਰਾਹੀਂ ਪ੍ਰਮਾਣਿਤ ਐਨਜੀਓ, ਕਲੀਨਿਕਾਂ ਅਤੇ ਲੋੜਵੰਦ ਮਰੀਜ਼ਾਂ ਨੂੰ ਮੁੜ ਵੰਡੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।',
    'cta.title': 'ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ ਗਰਿੱਡ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    'cta.desc': 'ਦਵਾਈਆਂ ਨੂੰ ਬਰਬਾਦ ਨਾ ਹੋਣ ਦਿਓ। ਸਾਰਿਆਂ ਲਈ ਸਿਹਤ ਸੰਭਾਲ ਨੂੰ ਸੁਲਭ ਬਣਾਉਣ ਵਾਲੇ ਹਜ਼ਾਰਾਂ ਲੋਕਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ।',
    'cta.start': 'ਹੁਣੇ ਦਾਨ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ',
    'cta.learn': 'ਹੋਰ ਜਾਣੋ',
    'auth.welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ!',
    'auth.join': 'ਗਰਿੱਡ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    'auth.loginDesc': 'ਸਾਡੇ ਨਾਲ ਜੁੜੇ ਰਹਿਣ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਨਾਲ ਲੌਗਇਨ ਕਰੋ',
    'auth.regDesc': 'ਆਪਣੇ ਨਿੱਜੀ ਵੇਰਵੇ ਦਰਜ ਕਰੋ ਅਤੇ ਸਾਡੇ ਨਾਲ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    'auth.create': 'ਖਾਤਾ ਬਣਾਓ',
    'auth.signin': 'ਸਾਈਨ ਇਨ',
    'auth.signup': 'ਸਾਈਨ ਅੱਪ',
    'auth.google': 'ਗੂਗਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    'auth.emailOr': 'ਜਾਂ ਈਮੇਲ ਦੀ ਵਰਤੋਂ ਕਰੋ',
    'auth.login': 'ਲੌਗਇਨ',
    'auth.registration': 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    'auth.identity': 'ਪਛਾਣ ਚੁਣੋ',
    'auth.email': 'ਈਮੇਲ ਪਤਾ',
    'auth.password': 'ਪਾਸਵਰਡ',
    'auth.remember': 'ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ',
    'auth.forgot': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    'auth.back': 'ਹੋਮ ਤੇ ਵਾਪਸ ਜਾਓ',
    'donor.title': 'ਦਾਨੀ ਡੈਸ਼ਬੋਰਡ',
    'donor.subtitle': 'ਆਪਣੇ ਪ੍ਰਭਾਵ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ ਅਤੇ ਆਪਣੇ ਦਾਨ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
    'donor.donate': 'ਦਵਾਈ ਦਾਨ ਕਰੋ',
    'donor.history': 'ਦਾਨ ਇਤਿਹਾਸ',
    'donor.impact': 'ਤੁਹਾਡਾ ਪ੍ਰਭਾਵ',
    'donor.saved': 'ਬਚਾਈਆਂ ਗਈਆਂ ਦਵਾਈਆਂ',
    'donor.lives': 'ਪ੍ਰਭਾਵਿਤ ਜੀਵਨ',
    'donor.points': 'ਮੈਡਪੁਆਇੰਟਸ ਕਮਾਏ',
    'receiver.title': 'ਬੇਨਤੀ ਕੇਂਦਰ',
    'receiver.subtitle': 'ਲੋੜਵੰਦਾਂ ਲਈ ਪ੍ਰਮਾਣਿਤ ਫਾਰਮਾਸਿਊਟੀਕਲ ਸਰਪਲੱਸ ਉਪਲਬਧ ਹੈ।',
    'receiver.newRequest': 'ਨਵੀਂ ਦਵਾਈ ਦੀ ਬੇਨਤੀ',
    'receiver.log': 'ਤੁਹਾਡਾ ਸਿਹਤ ਲੌਗ',
    'receiver.ayushman': 'ਆਯੁਸ਼ਮਾਨ ਆਈਡੀ ਦੀ ਪੜਤਾਲ ਕਰੋ',
    'receiver.ayushmanPlaceholder': 'ਆਯੁਸ਼ਮਾਨ ਆਈਡੀ ਦਰਜ ਕਰੋ (ਜਿਵੇਂ ABC)',
    'receiver.validate': 'ਖਾਤੇ ਦੀ ਪੜਤਾਲ ਕਰੋ',
    'receiver.invalidId': 'ਅਵੈਧ ਆਯੁਸ਼ਮਾਨ ਆਈਡੀ। ਕਿਰਪਾ ਕਰਕੇ ਪ੍ਰੋਟੋਟਾਈਪ ਸਿਮੂਲੇਸ਼ਨ ਲਈ "ABC" ਦੀ ਵਰਤੋਂ ਕਰੋ।',
    'receiver.uploadPrescription': 'ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਪਲੋਡ ਕਰੋ',
    'receiver.prescriptionDesc': 'ਕਿਰਪਾ ਕਰਕੇ ਪੜਤਾਲ ਲਈ ਆਪਣੀ ਮੈਡੀਕਲ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਪਲੋਡ ਕਰੋ।',
    'receiver.verifying': 'ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਦੀ ਪੜਤਾਲ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    'receiver.verified': 'ਪ੍ਰਮਾਣਿਤ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ',
    'receiver.verifiedDesc': 'ਤੁਹਾਡੀ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਦੀ ਪੜਤਾਲ ਹੋ ਗਈ ਹੈ। ਹੁਣ ਤੁਸੀਂ ਡਿਲੀਵਰੀ ਤੈਅ ਕਰ ਸਕਦੇ ਹੋ।',
    'receiver.schedule': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕਰੋ',
    'receiver.scheduling': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    'receiver.scheduled': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕੀਤੀ ਗਈ',
    'receiver.arrival': 'ਅਨੁਮਾਨਿਤ ਆਗਮਨ',
    'receiver.otp': 'ਡਿਲੀਵਰੀ ਓਟੀਪੀ',
    'receiver.otpDesc': 'ਡਿਲੀਵਰੀ ਪਾਰਟਨਰ ਨੂੰ ਇਹ ਓਟੀਪੀ ਦਿਖਾਓ।',
    'receiver.history': 'ਪਿਛਲੀਆਂ ਬੇਨਤੀਆਂ',
    'receiver.status.uploaded': 'ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਪਲੋਡ ਕੀਤੀ ਗਈ',
    'receiver.status.verified': 'ਪ੍ਰਮਾਣਿਤ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ',
    'receiver.status.scheduled': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕੀਤੀ ਗਈ',
    'receiver.status.completed': 'ਪੂਰਾ ਹੋਇਆ'
  },
  [Language.TAMIL]: {
    'nav.home': 'முகப்பு',
    'nav.donate': 'தானம் செய்',
    'nav.request': 'கோரிக்கை',
    'nav.ngo': 'என்ஜிஓ போர்டல்',
    'nav.gov': 'அரசு',
    'nav.about': 'பற்றி',
    'nav.translate': 'மொழிபெயர்ப்பு',
    'nav.signin': 'உள்நுழைக',
    'nav.getstarted': 'தொடங்குங்கள்',
    'nav.logout': 'வெளியேறு',
    'hero.badge': 'ஸ்மார்ட் மருந்து மறுவிநியோக நெட்வொர்க்',
    'hero.title': 'பயன்படுத்தப்படாத மருந்துகளை உயிர் காக்கும் வளங்களாக மாற்றுதல்',
    'hero.desc': 'மருந்து கழிவுகளை குறைக்கவும், உயிர்களைக் காக்கவும், அறிவார்ந்த மருந்து மறுவிநியோகம் மூலம் நிலையான சுகாதார சுற்றுச்சூழல் அமைப்பை உருவாக்கவும் எங்கள் நெட்வொர்க்கில் இணையுங்கள்.',
    'hero.donate': 'மருந்து தானம் செய்யுங்கள்',
    'hero.request': 'மருந்துகளைக் கோருங்கள்',
    'hero.partner': 'கூட்டாளராகுங்கள்',
    'stats.saved': 'சேமிக்கப்பட்ட மருந்துகள் (அலகுகள்)',
    'stats.lives': 'பாதிக்கப்பட்ட உயிர்கள்',
    'stats.co2': 'CO₂ குறைக்கப்பட்டது (கிலோ)',
    'stats.waste': 'தடுக்கப்பட்ட கழிவு (₹)',
    'map.title': 'நேரடி மருந்து விநியோக நெட்வொர்க்',
    'map.desc': 'நகரம் முழுவதும் நிகழ்நேர மருந்து ஓட்டங்கள், டிராப்-பாக்ஸ் இடங்கள் மற்றும் செயலில் உள்ள விநியோக வழிகளைக் கண்காணிக்கவும்',
    'map.dropbox': 'டிராப்-பாக்ஸ் இடங்கள்',
    'map.routes': 'செயலில் உள்ள வழிகள்',
    'map.delivered': 'இன்று விநியோகிக்கப்பட்டது',
    'how.title': 'இது எப்படி வேலை செய்கிறது',
    'how.desc': 'மூன்று படிகளில் எளிமையான, வெளிப்படையான மற்றும் திறமையான மருந்து மறுவிநியோகம்',
    'how.step1.title': 'சேகரிப்பு',
    'how.step1.desc': 'நன்கொடையாளர்கள் பயன்படுத்தப்படாத மருந்துகளை சரிபார்க்கப்பட்ட சேகரிப்பு மையங்களில் ஒப்படைக்கிறார்கள் அல்லது வீட்டிலிருந்து எடுக்கும் நேரத்தை திட்டமிடுகிறார்கள். ஒவ்வொரு நன்கொடையும் கண்காணிக்கப்பட்டு பதிவு செய்யப்படுகிறது.',
    'how.step2.title': 'சரிபார்ப்பு',
    'how.step2.desc': 'எங்கள் உரிமம் பெற்ற மருந்தாளுநர்கள் மற்றும் சரிபார்க்கப்பட்ட அமைப்புகள் முழுமையான பாதுகாப்பு மற்றும் நம்பகத்தன்மையை உறுதிப்படுத்த ஒவ்வொரு தொகுப்பிலும் கடுமையான மருத்துவ தணிக்கையைச் செய்கின்றன.',
    'how.step3.title': 'மறுவிநியோகம்',
    'how.step3.desc': 'மருந்துகள் எங்கள் பாதுகாப்பான தளவாட நெட்வொர்க் மூலம் சரிபார்க்கப்பட்ட என்ஜிஓக்கள், கிளினிக்குகள் மற்றும் தேவைப்படும் நோயாளிகளுக்கு மறுவிநியோகம் செய்யப்படுகின்றன.',
    'cta.title': 'உயிர் காக்கும் கட்டமைப்பில் இணையுங்கள்',
    'cta.desc': 'மருந்துகளை வீணாக்காதீர்கள். அனைவருக்கும் சுகாதார சேவையை அணுகக்கூடியதாக மாற்றும் ஆயிரக்கணக்கான மக்களுடன் இணையுங்கள்.',
    'cta.start': 'இப்போதே தானம் செய்யத் தொடங்குங்கள்',
    'cta.learn': 'மேலும் அறிய',
    'auth.welcome': 'மீண்டும் வருக!',
    'auth.join': 'கட்டமைப்பில் இணையுங்கள்',
    'auth.loginDesc': 'எங்களுடன் இணைந்திருக்க உங்கள் தனிப்பட்ட தகவலுடன் உள்நுழையவும்',
    'auth.regDesc': 'உங்கள் தனிப்பட்ட விவரங்களை உள்ளிட்டு எங்களுடன் பயணத்தைத் தொடங்குங்கள்',
    'auth.create': 'கணக்கை உருவாக்கு',
    'auth.signin': 'உள்நுழைக',
    'auth.signup': 'பதிவு செய்க',
    'auth.google': 'கூகுள் மூலம் உள்நுழைக',
    'auth.emailOr': 'அல்லது மின்னஞ்சலைப் பயன்படுத்தவும்',
    'auth.login': 'உள்நுழைவு',
    'auth.registration': 'பதிவு',
    'auth.identity': 'அடையாளத்தைத் தேர்ந்தெடுக்கவும்',
    'auth.email': 'மின்னஞ்சல் முகவரி',
    'auth.password': 'கடவுச்சொல்',
    'auth.remember': 'என்னை நினைவில் கொள்',
    'auth.forgot': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'auth.back': 'முகப்பிற்குச் செல்லவும்',
    'donor.title': 'நன்கொடையாளர் டாஷ்போர்டு',
    'donor.subtitle': 'உங்கள் தாக்கத்தைக் கண்காணித்து உங்கள் நன்கொடைகளை நிர்வகிக்கவும்',
    'donor.donate': 'மருந்து தானம் செய்',
    'donor.history': 'நன்கொடை வரலாறு',
    'donor.impact': 'உங்கள் தாக்கம்',
    'donor.saved': 'சேமிக்கப்பட்ட மருந்துகள்',
    'donor.lives': 'பாதிக்கப்பட்ட உயிர்கள்',
    'donor.points': 'பெற்ற மெட்பாயிண்ட்ஸ்',
    'receiver.title': 'கோரிக்கை மையம்',
    'receiver.subtitle': 'தேவைப்படுபவர்களுக்கு சரிபார்க்கப்பட்ட மருந்து உபரி கிடைக்கிறது.',
    'receiver.newRequest': 'புதிய மருந்து கோரிக்கை',
    'receiver.log': 'உங்கள் சுகாதார பதிவு',
    'receiver.ayushman': 'ஆயுஷ்மான் ஐடியை சரிபார்க்கவும்',
    'receiver.ayushmanPlaceholder': 'ஆயுஷ்மான் ஐடியை உள்ளிடவும் (எ.கா. ABC)',
    'receiver.validate': 'கணக்கை சரிபார்க்கவும்',
    'receiver.invalidId': 'தவறான ஆயுஷ்மான் ஐடி. முன்மாதிரி உருவகப்படுத்துதலுக்கு "ABC" ஐப் பயன்படுத்தவும்.',
    'receiver.uploadPrescription': 'மருந்துச் சீட்டைப் பதிவேற்றவும்',
    'receiver.prescriptionDesc': 'சரிபார்ப்பிற்காக உங்கள் மருத்துவ மருந்துச் சீட்டைப் பதிவேற்றவும்.',
    'receiver.verifying': 'மருந்துச் சீட்டு சரிபார்க்கப்படுகிறது...',
    'receiver.verified': 'சரிபார்க்கப்பட்ட மருந்துச் சீட்டு',
    'receiver.verifiedDesc': 'உங்கள் மருந்துச் சீட்டு சரிபார்க்கப்பட்டது. நீங்கள் இப்போது விநியோகத்தைத் திட்டமிடலாம்.',
    'receiver.schedule': 'விநியோகத்தைத் திட்டமிடுங்கள்',
    'receiver.scheduling': 'விநியோகம் திட்டமிடப்படுகிறது...',
    'receiver.scheduled': 'விநியோகம் திட்டமிடப்பட்டது',
    'receiver.arrival': 'மதிப்பிடப்பட்ட வருகை',
    'receiver.otp': 'விநியோக OTP',
    'receiver.otpDesc': 'இந்த OTP ஐ விநியோக கூட்டாளரிடம் காட்டவும்.',
    'receiver.history': 'முந்தைய கோரிக்கைகள்',
    'receiver.status.uploaded': 'மருந்துச் சீட்டு பதிவேற்றப்பட்டது',
    'receiver.status.verified': 'சரிபார்க்கப்பட்ட மருந்துச் சீட்டு',
    'receiver.status.scheduled': 'விநியோகம் திட்டமிடப்பட்டது',
    'receiver.status.completed': 'முடிந்தது'
  },
  [Language.MARATHI]: {
    'nav.home': 'होम',
    'nav.donate': 'दान करा',
    'nav.request': 'विनंती',
    'nav.ngo': 'एनजीओ पोर्टल',
    'nav.gov': 'सरकार',
    'nav.about': 'बद्दल',
    'nav.translate': 'अनुवाद',
    'nav.signin': 'साइन इन',
    'nav.getstarted': 'सुरू करा',
    'nav.logout': 'लॉगआउट',
    'hero.badge': 'स्मार्ट औषध पुनर्वितरण नेटवर्क',
    'hero.title': 'न वापरलेल्या औषधांचे जीवनरक्षक संसाधनांमध्ये रूपांतर करणे',
    'hero.desc': 'फार्मास्युटिकल कचरा कमी करण्यासाठी, जीव वाचवण्यासाठी आणि बुद्धिमान औषध पुनर्वितरणाद्वारे शाश्वत आरोग्य सेवा परिसंस्था तयार करण्यासाठी आमच्या नेटवर्कमध्ये सामील व्हा.',
    'hero.donate': 'औषध दान करा',
    'hero.request': 'औषधांची विनंती करा',
    'hero.partner': 'भागीदार व्हा',
    'stats.saved': 'वाचवलेली औषधे (युनिट्स)',
    'stats.lives': 'प्रभावित जीवन',
    'stats.co2': 'CO₂ कमी झाले (किलो)',
    'stats.waste': 'टाळलेला कचरा (₹)',
    'map.title': 'थेट औषध वितरण नेटवर्क',
    'map.desc': 'शहरभर रिअल-टाइम औषध प्रवाह, ड्रॉप-बॉक्स ठिकाणे आणि सक्रिय वितरण मार्ग ट्रॅक करा',
    'map.dropbox': 'ड्रॉप-बॉक्स ठिकाणे',
    'map.routes': 'सक्रिय मार्ग',
    'map.delivered': 'आज वितरित',
    'how.title': 'हे कसे कार्य करते',
    'how.desc': 'तीन चरणांमध्ये सोपे, पारदर्शक आणि कार्यक्षम औषध पुनर्वितरण',
    'how.step1.title': 'संकलन',
    'how.step1.desc': 'दाते न वापरलेली औषधे सत्यापित संकलन केंद्रांवर सोडतात किंवा होम पिकअप शेड्यूल करतात. प्रत्येक देणगीचा मागोवा घेतला जातो आणि नोंद केली जाते.',
    'how.step2.title': 'सत्यापन',
    'how.step2.desc': 'आमचे परवानाधारक फार्मासिस्ट आणि सत्यापित प्रणाली पूर्ण सुरक्षा आणि सत्यता सुनिश्चित करण्यासाठी प्रत्येक बॅचवर कठोर क्लिनिकल ऑडिट करतात.',
    'how.step3.title': 'पुनर्निर्देशन',
    'how.step3.desc': 'आमच्या सुरक्षित लॉजिस्टिक नेटवर्कद्वारे सत्यापित एनजीओ, दवाखाने आणि गरजू रुग्णांना औषधे पुनर्वितरित केली जातात.',
    'cta.title': 'जीवनरक्षक ग्रिडमध्ये सामील व्हा',
    'cta.desc': 'औषधे वाया जाऊ देऊ नका. सर्वांसाठी आरोग्य सेवा सुलभ करणाऱ्या हजारो लोकांमध्ये सामील व्हा.',
    'cta.start': 'आता दान करण्यास सुरुवात करा',
    'cta.learn': 'अधिक जाणून घ्या',
    'auth.welcome': 'पुन्हा स्वागत आहे!',
    'auth.join': 'ग्रिडमध्ये सामील व्हा',
    'auth.loginDesc': 'आमच्याशी जोडलेले राहण्यासाठी कृपया तुमच्या वैयक्तिक माहितीसह लॉगिन करा',
    'auth.regDesc': 'तुमचा वैयक्तिक तपशील प्रविष्ट करा और आमच्यासह प्रवास सुरू करा',
    'auth.create': 'खाते तयार करा',
    'auth.signin': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.google': 'गूगलसह साइन इन करा',
    'auth.emailOr': 'किंवा ईमेल वापरा',
    'auth.login': 'लॉगिन',
    'auth.registration': 'नोंदणी',
    'auth.identity': 'ओळख निवडा',
    'auth.email': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.remember': 'माझी आठवण ठेवा',
    'auth.forgot': 'पासवर्ड विसरलात?',
    'auth.back': 'होमवर परत जा',
    'donor.title': 'दाता डॅशबोर्ड',
    'donor.subtitle': 'तुमच्या प्रभावाचा मागोवा घ्या आणि तुमच्या देणग्या व्यवस्थापित करा',
    'donor.donate': 'औषध दान करा',
    'donor.history': 'देणगी इतिहास',
    'donor.impact': 'तुमचा प्रभाव',
    'donor.saved': 'वाचवलेली औषधे',
    'donor.lives': 'प्रभावित जीवन',
    'donor.points': 'मेडपॉइंट्स मिळवले',
    'receiver.title': 'विनंती केंद्र',
    'receiver.subtitle': 'गरजू लोकांसाठी सत्यापित फार्मास्युटिकल अधिशेष उपलब्ध आहे.',
    'receiver.newRequest': 'नवीन औषध विनंती',
    'receiver.log': 'तुमचा आरोग्य लॉग',
    'receiver.ayushman': 'आयुष्मान आयडी सत्यापित करा',
    'receiver.ayushmanPlaceholder': 'आयुष्मान आयडी प्रविष्ट करा (उदा. ABC)',
    'receiver.validate': 'खाते सत्यापित करा',
    'receiver.invalidId': 'अवैध आयुष्मान आयडी. कृपया प्रोटोटाइप सिम्युलेशनसाठी "ABC" वापरा.',
    'receiver.uploadPrescription': 'प्रिस्क्रिप्शन अपलोड करा',
    'receiver.prescriptionDesc': 'कृपया सत्यापनासाठी तुमचे मेडिकल प्रिस्क्रिप्शन अपलोड करा.',
    'receiver.verifying': 'प्रिस्क्रिप्शन सत्यापित केले जात आहे...',
    'receiver.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.verifiedDesc': 'तुमचे प्रिस्क्रिप्शन सत्यापित झाले आहे. तुम्ही आता डिलिव्हरी शेड्यूल करू शकता.',
    'receiver.schedule': 'डिलिव्हरी शेड्यूल करा',
    'receiver.scheduling': 'डिलिव्हरी शेड्यूल केली जात आहे...',
    'receiver.scheduled': 'डिलिव्हरी शेड्यूल केली',
    'receiver.arrival': 'अंदाजित आगमन',
    'receiver.otp': 'डिलिव्हरी ओटीपी',
    'receiver.otpDesc': 'डिलिव्हरी पार्टनरला हा ओटीपी दाखवा.',
    'receiver.history': 'मागील विनंत्या',
    'receiver.status.uploaded': 'प्रिस्क्रिप्शन अपलोड केले',
    'receiver.status.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.status.scheduled': 'डिलिव्हरी शेड्यूल केली',
    'receiver.status.completed': 'पूर्ण झाले'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(Language.ENGLISH);

  const t = (key: string): string => {
    return translations[language][key] || translations[Language.ENGLISH][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
